
const singleUser = [
  [
    "login",
    "danielOuattara"
  ],
  [
    "id",
    67764936
  ],
  [
    "node_id",
    "MDQ6VXNlcjY3NzY0OTM2"
  ],
  [
    "avatar_url",
    "https://avatars.githubusercontent.com/u/67764936?v=4"
  ],
  [
    "gravatar_id",
    ""
  ],
  [
    "url",
    "https://api.github.com/users/danielOuattara"
  ],
  [
    "html_url",
    "https://github.com/danielOuattara"
  ],
  [
    "followers_url",
    "https://api.github.com/users/danielOuattara/followers"
  ],
  [
    "following_url",
    "https://api.github.com/users/danielOuattara/following{/other_user}"
  ],
  [
    "gists_url",
    "https://api.github.com/users/danielOuattara/gists{/gist_id}"
  ],
  [
    "starred_url",
    "https://api.github.com/users/danielOuattara/starred{/owner}{/repo}"
  ],
  [
    "subscriptions_url",
    "https://api.github.com/users/danielOuattara/subscriptions"
  ],
  [
    "organizations_url",
    "https://api.github.com/users/danielOuattara/orgs"
  ],
  [
    "repos_url",
    "https://api.github.com/users/danielOuattara/repos"
  ],
  [
    "events_url",
    "https://api.github.com/users/danielOuattara/events{/privacy}"
  ],
  [
    "received_events_url",
    "https://api.github.com/users/danielOuattara/received_events"
  ],
  [
    "type",
    "User"
  ],
  [
    "site_admin",
    false
  ],
  [
    "name",
    "Daniel OUATTARA"
  ],
  [
    "company",
    null
  ],
  [
    "blog",
    ""
  ],
  [
    "location",
    "Combs la ville, France"
  ],
  [
    "email",
    null
  ],
  [
    "hireable",
    true
  ],
  [
    "bio",
    null
  ],
  [
    "twitter_username",
    null
  ],
  [
    "public_repos",
    128
  ],
  [
    "public_gists",
    0
  ],
  [
    "followers",
    1
  ],
  [
    "following",
    15
  ],
  [
    "created_at",
    "2020-07-02T22:43:46Z"
  ],
  [
    "updated_at",
    "2023-01-14T11:31:39Z"
  ]
]


export default singleUser;